######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:15:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += renderArea.h window.h
SOURCES += main.cpp renderArea.cpp window.cpp
RESOURCES += basicdrawing.qrc
