######################################################################
# Automatically generated by qmake (2.01a) mar. août 21 15:35:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
