######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 16:01:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += transform.cpp
