######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 15:35:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += rubber.cpp
