######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 16:05:30 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myProxy.h myScene.h
SOURCES += main.cpp myProxy.cpp myScene.cpp
