######################################################################
# Automatically generated by qmake (2.01a) mer. août 29 11:19:03 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
