######################################################################
# Automatically generated by qmake (2.01a) lun. août 27 18:36:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
