######################################################################
# Automatically generated by qmake (2.01a) ven. juil. 20 09:46:25 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mdi.cpp
