######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:14:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sigslot.h
SOURCES += main.cpp sigslot.cpp
