######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 18 15:52:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
