######################################################################
# Automatically generated by qmake (2.01a) lun. sept. 15 09:14:09 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
