######################################################################
# Automatically generated by qmake (2.01a) mer. août 22 09:24:07 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
