######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 17:21:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += proxy.cpp
