######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 15:37:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myPainter.h
SOURCES += main.cpp myPainter.cpp
