######################################################################
# Automatically generated by qmake (2.01a) mar. mars 18 11:21:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connection.h
SOURCES += model.cpp
