######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:13:06 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += painter.h
SOURCES += main.cpp painter.cpp
