######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:37:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += mainWindow.cpp
