######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 17:22:50 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h
SOURCES += main.cpp myDialog.cpp
