######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:10:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += MainWindow-1.qrc
