######################################################################
# Automatically generated by qmake (2.01a) mer. sept. 5 11:11:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
