######################################################################
# Automatically generated by qmake (2.01a) lun. mars 18 15:28:47 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += action.cpp
