######################################################################
# Automatically generated by qmake (2.01a) mer. juil. 18 15:24:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
