######################################################################
# Automatically generated by qmake (2.01a) mar. mars 12 11:03:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
